[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "b1.7.3"
quilt_loader = "0.18.1-beta.60"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }
